### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by ghost** [Alexrs95/shield-study-rappor#12]
FYI: The following changes were made to this repository's wiki:

- defacing spam has been removed

- Restricting write access to contributors is strongly encouraged.  Please [make that change](https://github.com/mozilla/shield-study-rappor/settings)  ([documentation](https://help.github.com/articles/changing-access-permissions-for-wikis/)).

These were made as the result of a recent automated defacement of publically writeable wikis.

**Comment by Dexterp37** [comment]
Thanks. I don't have the privileges to remove the wikis on this repo. Did you already fix the problem or is there any action I should take here?

**Comment by ghost** [comment]
Thanks for the follow up. I just now disabled the wiki, as it wasn't being used. 

No further action needed.
