### ISSUE TITLE
Refactor encode method to work better with RAPPOR simulator.

### ISSUE THREAD

**Issue by alexrs** [Alexrs95/shield-study-rappor#7]
https://github.com/Alexrs95/shield-study-rappor/blob/b6716b90450b711f0832b1bf85766e300f052ef2/addon/TelemetryRappor.jsm#L150

**Comment by Dexterp37** [comment]
Hey Alejandro, could you please comment with why is this needed and what's the planned refactoring?

**Comment by Dexterp37** [comment]
This was fixed.
